import json
from typing import Dict, Any, List

try:
    from shared.models import PlannedMCPBlueprint, ParameterLocation
except ImportError:
    from models import PlannedMCPBlueprint, ParameterLocation


class CoderAgent:
    """
    Generates production-grade FastMCP server code, test harness, client configuration,
    and dependency manifests with connection pooling, secret redaction, and error boundaries.
    """

    @classmethod
    def generate_bundle(cls, blueprint: PlannedMCPBlueprint) -> Dict[str, Any]:
        server_code = cls._generate_server_code(blueprint)
        requirements = cls._generate_requirements()
        test_protocol = cls._generate_test_protocol(blueprint)
        run_tests_code = cls._generate_test_runner_code(blueprint)
        client_config = cls._generate_client_config(blueprint)

        return {
            "server.py": server_code,
            "requirements.txt": requirements,
            "test_protocol.json": test_protocol,
            "run_tests.py": run_tests_code,
            "claude_desktop_config.json": client_config,
            "metadata": {
                "service_name": blueprint.service_name,
                "base_url": blueprint.base_url,
                "auth_type": blueprint.auth.auth_type,
                "auth_env_var": blueprint.auth.env_var_name,
                "tool_count": len(blueprint.tools),
                "tools": [t.tool_name for t in blueprint.tools],
            }
        }

    @classmethod
    def _generate_server_code(cls, bp: PlannedMCPBlueprint) -> str:
        lines: List[str] = [
            '"""',
            f'FastMCP Server for {bp.service_name}',
            'Auto-generated by MCP-Forge with Connection Pooling, Type Safety, and Defensive Guardrails',
            '"""',
            'import os',
            'import json',
            'import re',
            'import asyncio',
            'import httpx',
            'from typing import Optional, List, Dict, Any, Union',
            'try:',
            '    from mcp.server.fastmcp import FastMCP',
            'except (ImportError, ModuleNotFoundError):',
            '    try:',
            '        from mcp.server.mcpserver import MCPServer as FastMCP',
            '    except (ImportError, ModuleNotFoundError):',
            '        class FastMCP:',
            '            def __init__(self, name: str): self.name = name',
            '            def tool(self, description: str = ""):',
            '                def decorator(fn):',
            '                    fn.description = description',
            '                    return fn',
            '                return decorator',
            '            def run(self): pass',
            'from dotenv import load_dotenv',
            '',
            'load_dotenv()',
            '',
            f'mcp = FastMCP("{bp.service_name}")',
            f'BASE_URL = os.getenv("API_BASE_URL", "{bp.base_url}").rstrip("/")',
            f'AUTH_TOKEN = os.getenv("{bp.auth.env_var_name}", "")',
            '',
            '# Global Connection Pool with keep-alive limits and bounded timeouts',
            '_HTTP_CLIENT: Optional[httpx.AsyncClient] = None',
            '',
            'def get_http_client() -> httpx.AsyncClient:',
            '    global _HTTP_CLIENT',
            '    if _HTTP_CLIENT is None or _HTTP_CLIENT.is_closed:',
            '        _HTTP_CLIENT = httpx.AsyncClient(',
            '            timeout=httpx.Timeout(30.0, connect=10.0),',
            '            limits=httpx.Limits(max_keepalive_connections=20, max_connections=100, keepalive_expiry=30.0),',
            '            follow_redirects=True,',
            '        )',
            '    return _HTTP_CLIENT',
            '',
            'def _get_headers() -> Dict[str, str]:',
            '    headers = {',
            '        "User-Agent": "MCP-Forge-Autonomous-Agent/2.0",',
            '        "Accept": "application/vnd.github+json, application/json, */*",',
            '    }',
        ]

        if bp.auth.auth_type != "none":
            lines.append('    if AUTH_TOKEN:')
            if bp.auth.auth_type == "bearer":
                lines.append('        headers["Authorization"] = f"Bearer {AUTH_TOKEN}"')
            elif bp.auth.auth_type == "header":
                lines.append(f'        headers["{bp.auth.header_name}"] = AUTH_TOKEN')
            elif bp.auth.auth_type == "basic":
                lines.append('        headers["Authorization"] = f"Basic {AUTH_TOKEN}"')
            elif bp.auth.auth_type == "query":
                pass

        lines.extend([
            '    return headers',
            '',
            'def _sanitize_output(val: Any) -> str:',
            '    """Sanitizes text and redacts sensitive tokens and secrets before emitting to LLM."""',
            '    if val is None:',
            '        return ""',
            '    text = str(val) if not isinstance(val, str) else val',
            '    if AUTH_TOKEN and len(AUTH_TOKEN) > 4:',
            '        text = text.replace(AUTH_TOKEN, "[REDACTED_SECRET]")',
            r'    text = re.sub(r"(Bearer\s+)[A-Za-z0-9_\-\.]{8,}", r"\1[REDACTED_TOKEN]", text, flags=re.IGNORECASE)',
            r'    text = re.sub(r"(ghp_[A-Za-z0-9]{30,})", "[REDACTED_GITHUB_TOKEN]", text)',
            '    return text',
            '',
        ])

        for tool in bp.tools:
            doc = tool.docstring.replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ')
            param_defs: List[str] = []
            path_mappings: List[tuple] = []
            query_mappings: List[tuple] = []
            body_mappings: List[tuple] = []

            req_params = [p for p in tool.parameters if p.required and "Optional" not in p.python_type]
            opt_params = [p for p in tool.parameters if not p.required or "Optional" in p.python_type]

            for p in req_params:
                wire_name = p.raw_name or p.name
                param_defs.append(f"{p.name}: {p.python_type}")
                if p.location == ParameterLocation.PATH:
                    path_mappings.append((p.name, wire_name))
                elif p.location == ParameterLocation.BODY:
                    body_mappings.append((p.name, wire_name))
                else:
                    query_mappings.append((p.name, wire_name))

            for p in opt_params:
                wire_name = p.raw_name or p.name
                param_defs.append(f"{p.name}: {p.python_type} = None")
                if p.location == ParameterLocation.PATH:
                    path_mappings.append((p.name, wire_name))
                elif p.location == ParameterLocation.BODY:
                    body_mappings.append((p.name, wire_name))
                else:
                    query_mappings.append((p.name, wire_name))

            param_sig = ", ".join(param_defs)

            lines.append(f'@mcp.tool(description="{doc}")')
            lines.append(f'async def {tool.tool_name}({param_sig}) -> str:')
            lines.append(f'    """{doc}"""')
            lines.append('    client = get_http_client()')
            
            # Formulate Path Substitution
            formatted_path = tool.endpoint_path
            for py_name, wire_name in path_mappings:
                formatted_path = formatted_path.replace(f"{{{wire_name}}}", f"{{{py_name}}}")

            lines.append(f'    endpoint = f"{formatted_path}"')
            lines.append('    url = f"{BASE_URL}{endpoint}"')

            # Assemble Query Params
            lines.append('    query_params: Dict[str, Any] = {}')
            if bp.auth.auth_type == "query" and bp.auth.query_param_name:
                lines.append(f'    if AUTH_TOKEN:\n        query_params["{bp.auth.query_param_name}"] = AUTH_TOKEN')

            for py_name, wire_name in query_mappings:
                lines.append(f'    if {py_name} is not None:\n        query_params["{wire_name}"] = {py_name}')

            # Assemble JSON Body
            lines.append('    json_body: Dict[str, Any] = {}')
            for py_name, wire_name in body_mappings:
                lines.append(f'    if {py_name} is not None:\n        json_body["{wire_name}"] = {py_name}')

            lines.extend([
                '    try:',
            ])

            http_m = tool.http_method.upper()
            if http_m == "GET":
                lines.append('        response = await client.get(url, params=query_params or None, headers=_get_headers())')
            elif http_m == "POST":
                lines.append('        response = await client.post(url, params=query_params or None, json=json_body or None, headers=_get_headers())')
            elif http_m == "PUT":
                lines.append('        response = await client.put(url, params=query_params or None, json=json_body or None, headers=_get_headers())')
            elif http_m == "DELETE":
                lines.append('        response = await client.delete(url, params=query_params or None, headers=_get_headers())')
            elif http_m == "PATCH":
                lines.append('        response = await client.patch(url, params=query_params or None, json=json_body or None, headers=_get_headers())')
            else:
                lines.append(f'        response = await client.request("{http_m}", url, params=query_params or None, json=json_body or None, headers=_get_headers())')

            lines.extend([
                '        response.raise_for_status()',
                '        try:',
                '            return _sanitize_output(json.dumps(response.json(), indent=2))',
                '        except Exception:',
                '            return _sanitize_output(response.text)',
                '    except httpx.HTTPStatusError as e:',
                '        return _sanitize_output(f"HTTP Error {e.response.status_code}: {e.response.text}")',
                '    except httpx.TimeoutException as e:',
                '        return _sanitize_output(f"Execution Error: Request timed out after 30.0s ({str(e)})")',
                '    except Exception as e:',
                '        return _sanitize_output(f"Execution Error: {str(e)}")',
                '',
            ])

        lines.extend([
            'if __name__ == "__main__":',
            '    mcp.run()',
            '',
        ])
        return "\n".join(lines)

    @staticmethod
    def _generate_requirements() -> str:
        return "mcp>=1.0.0\nhttpx>=0.28.0\npydantic>=2.0.0\npython-dotenv>=1.0.0\n"

    @staticmethod
    def _generate_test_protocol(bp: PlannedMCPBlueprint) -> Dict[str, Any]:
        tests = []
        for tool in bp.tools:
            for tc in tool.test_cases:
                tests.append({
                    "test_id": tc.test_id,
                    "tool_name": tool.tool_name,
                    "description": tc.description,
                    "arguments": tc.input_arguments,
                    "test_payload": tc.input_arguments,
                    "expected_http_status": tc.expected_http_status,
                })
        return {
            "service_name": bp.service_name,
            "base_url": bp.base_url,
            "auth_env_var": bp.auth.env_var_name,
            "tests": tests,
        }

    @staticmethod
    def _generate_test_runner_code(bp: PlannedMCPBlueprint) -> str:
        return f'''"""
Automated Daytona Test Driver for {bp.service_name} MCP Server
Executed inside Daytona Sandbox to test all tools with JSON-RPC semantics.
"""
import sys
import os
import json
import time
import inspect
import asyncio

# Ensure local module resolution within Daytona sandbox
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ".")

async def run_all_tests():
    print("[Daytona Test Driver] Loading test_protocol.json...")
    protocol_path = "test_protocol.json"
    if not os.path.exists(protocol_path):
        protocol_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "test_protocol.json")

    with open(protocol_path, "r", encoding="utf-8") as f:
        protocol = json.load(f)

    tests_list = protocol.get("tests") or protocol.get("test_suites") or []
    # Normalize nested suites if present
    flattened_tests = []
    for item in tests_list:
        if "tests" in item and isinstance(item["tests"], list):
            for sub_test in item["tests"]:
                sub_test["tool_name"] = sub_test.get("tool_name") or item.get("tool_name")
                flattened_tests.append(sub_test)
        else:
            flattened_tests.append(item)

    report = {{
        "status": "PASS",
        "stage": "functional_testing",
        "sandbox_id": os.getenv("DAYTONA_SANDBOX_ID", "sandbox-local"),
        "service_name": protocol.get("service_name"),
        "total_tests": len(flattened_tests),
        "passed_count": 0,
        "failed_count": 0,
        "tool_results": [],
        "results": []
    }}

    import server

    for test in flattened_tests:
        tool_name = test["tool_name"]
        args = test.get("arguments") or test.get("test_payload") or {{}}
        start_time = time.time()
        print(f"[Testing] Invoking tool '{{tool_name}}' with args: {{args}}")
        
        func = getattr(server, tool_name, None)
        if not func:
            report["status"] = "FAIL"
            report["failed_count"] += 1
            err_res = {{
                "tool_name": tool_name,
                "status": "FAIL",
                "latency_ms": 0,
                "error": f"Tool function '{{tool_name}}' not found on server module"
            }}
            report["results"].append(err_res)
            report["tool_results"].append(err_res)
            continue

        try:
            # FastMCP Tool wrapper unwrapping
            callable_fn = getattr(func, "fn", func)
            if inspect.iscoroutinefunction(callable_fn):
                result = await callable_fn(**args)
            elif callable(callable_fn):
                result = callable_fn(**args)
            else:
                result = await func(**args)

            duration_ms = int((time.time() - start_time) * 1000)
            
            # Runtime crash detection vs standard HTTP remote responses
            is_error = isinstance(result, str) and ("Execution Error:" in result)
            status = "FAIL" if is_error else "PASS"
            
            if is_error:
                report["status"] = "FAIL"
                report["failed_count"] += 1
            else:
                report["passed_count"] += 1

            res_entry = {{
                "tool_name": tool_name,
                "status": status,
                "latency_ms": duration_ms,
                "response_sample": result[:200] if isinstance(result, str) else str(result)[:200],
                "output_preview": result[:200] if isinstance(result, str) else str(result)[:200],
                "error": result if is_error else None
            }}
            report["results"].append(res_entry)
            report["tool_results"].append(res_entry)
        except Exception as e:
            report["status"] = "FAIL"
            report["failed_count"] += 1
            err_entry = {{
                "tool_name": tool_name,
                "status": "FAIL",
                "latency_ms": int((time.time() - start_time) * 1000),
                "error": str(e)
            }}
            report["results"].append(err_entry)
            report["tool_results"].append(err_entry)

    report["status"] = "PASS" if report["failed_count"] == 0 else "FAIL"

    with open("test_report.json", "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    print(f"[Daytona Test Driver] Completed. Status: {{report['status']}} (Passed: {{report['passed_count']}}/{{report['total_tests']}})")
    sys.exit(0 if report["status"] == "PASS" else 1)

if __name__ == "__main__":
    asyncio.run(run_all_tests())
'''

    @staticmethod
    def _generate_client_config(bp: PlannedMCPBlueprint) -> Dict[str, Any]:
        env_var = bp.auth.env_var_name or "API_KEY"
        if env_var.startswith(("ghp_", "sk-", "Bearer", "ey")) or len(env_var) > 25 or not env_var.isidentifier():
            env_var = "GITHUB_TOKEN" if "github" in bp.service_name.lower() else "API_KEY"

        return {
            "mcpServers": {
                bp.service_name.lower(): {
                    "command": "python",
                    "args": ["server.py"],
                    "env": {
                        env_var: f"YOUR_{env_var}_HERE",
                        "API_BASE_URL": bp.base_url,
                    }
                }
            }
        }

